"对齐" = "alignment"
"异步函数" = "async function"
"动态分发" = "dynamic dispatch"
"存在类型" = "existential type"
"单态化" = "monomorphization"
"空指针优化" = "null pointer optimization"
"空指针安全" = "null safety"
"切片" = "slice"
"特质" = "trait"
"特质对象" = "trait object"
"虚表" = "vtable"
"零开销抽象" = "zero-cost abstractions"
